name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['12.x', '14.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: Lint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint # will run `yarn lint` command

      - name: Test
        uses: borales/actions-yarn@v4
        with:
          cmd: test --ci --coverage --maxWorkers=2 # will run `yarn test --ci --coverage --maxWorkers=2` command

      - name: Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command
